services:
  api:
    build: ./server
    container_name: hello_api
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    depends_on:
      - db
      - ollama
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_sum
    ports:
      - "11434:11434"

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
